### ISSUE TITLE
无法定位程序输入点，还缺少好多动态dll

### ISSUE THREAD

**Issue by rogerfederal** [Kdwkakcs/singtools#1]
![微信图片_20241112164853](https://github.com/user-attachments/assets/8e82ada0-6bef-4ac2-98fc-dd7e0ad5f474)

**Comment by Kdwkakcs** [comment]
可以提供更多的信息吗？你的windows版本，我这里在github action中测试完全没有问题。运行的方式的话在powershell或者cmd中使用，具体可以参考readme中的内容。config.json实例文件我已经提供了一个参考

**Comment by rogerfederal** [comment]
> 可以提供更多的信息吗？你的windows版本，我这里在github action中测试完全没有问题。运行的方式的话在powershell或者cmd中使用，具体可以参考readme中的内容。config.json实例文件我已经提供了一个参考
已测试，win11专业版，64位，不太确定是否缺少什么
![微信图片_20241113124509](https://github.com/user-attachments/assets/e0672022-2914-424e-8021-3da569d6043a)
![微信图片_20241113124633](https://github.com/user-attachments/assets/f141205a-580c-4a52-b3fc-ba52cdd4fc99)

**Comment by rogerfederal** [comment]
> 可以提供更多的信息吗？你的windows版本，我这里在github action中测试完全没有问题。运行的方式的话在powershell或者cmd中使用，具体可以参考readme中的内容。config.json实例文件我已经提供了一个参考

我根据提示，补充了这几个动态DLL，不清楚是不是这几个动态DLL引起的
![微信图片_20241113125030](https://github.com/user-attachments/assets/c8a7ca3d-872d-434f-817a-69128485f46c)

**Comment by Kdwkakcs** [comment]
https://github.com/Kdwkakcs/singtools/releases/tag/v0.1.2 你试试现在这个版本是否正常的解决了动态库的问题？如果使用中有设么其他的问题或者建议，欢迎提issues。ps：README进行了更新，看看使用中是否还需要添加其他的信息

**Comment by Kdwkakcs** [comment]
> > 可以提供更多的信息吗？你的windows版本，我这里在github action中测试完全没有问题。运行的方式的话在powershell或者cmd中使用，具体可以参考readme中的内容。config.json实例文件我已经提供了一个参考
> > 已测试，win11专业版，64位，不太确定是否缺少什么
> > ![微信图片_20241113124509](https://private-user-images.githubusercontent.com/26449654/385588826-e0672022-2914-424e-8021-3da569d6043a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTU5ODEsIm5iZiI6MTczMTQ5NTY4MSwicGF0aCI6Ii8yNjQ0OTY1NC8zODU1ODg4MjYtZTA2NzIwMjItMjkxNC00MjRlLTgwMjEtM2RhNTY5ZDYwNDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGQ1MzU5OTgzMDdiZDJhNmI1NjFkZDc1ZTQyOWEyMTdjZTllNTg1NDFhNDYyNTA1ZGEzYWFiYTY5YmUyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eBKprFgOnm05SRpkLZcguNDK-2VAG2WAXsI9inJoM0E)
> > ![微信图片_20241113124633](https://private-user-images.githubusercontent.com/26449654/385588848-f141205a-580c-4a52-b3fc-ba52cdd4fc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTU5ODEsIm5iZiI6MTczMTQ5NTY4MSwicGF0aCI6Ii8yNjQ0OTY1NC8zODU1ODg4NDgtZjE0MTIwNWEtNTgwYy00YTUyLWIzZmMtYmE1MmNkZDRmYzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzN2Y0NjEzYmFmMjdiOWJjOGRiM2Y0MmZhOTIwNTBmYzVlM2M4ZGE4MDU4ZTQwZWFkMGJhZTU4NjZjZjJjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hCb4EYteM3ED-OvszgS7lbgyNlgLX6adgLP3jnVHU9s)

<img width="1153" alt="图片" src="https://github.com/user-attachments/assets/45a19106-369f-4540-9366-99b850a241d8">
目录下的文件和对应的参数应该如图，需要加上相对路径才能找到运行程序，并且windows下的可执行文件以.exe结尾。

**Comment by rogerfederal** [comment]
> > > 可以提供更多的信息吗？你的windows版本，我这里在github action中测试完全没有问题。运行的方式的话在powershell或者cmd中使用，具体可以参考readme中的内容。config.json实例文件我已经提供了一个参考
> > > 已测试，win11专业版，64位，不太确定是否缺少什么
> > > ![微信图片_20241113124509](https://private-user-images.githubusercontent.com/26449654/385588826-e0672022-2914-424e-8021-3da569d6043a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTU5ODEsIm5iZiI6MTczMTQ5NTY4MSwicGF0aCI6Ii8yNjQ0OTY1NC8zODU1ODg4MjYtZTA2NzIwMjItMjkxNC00MjRlLTgwMjEtM2RhNTY5ZDYwNDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGQ1MzU5OTgzMDdiZDJhNmI1NjFkZDc1ZTQyOWEyMTdjZTllNTg1NDFhNDYyNTA1ZGEzYWFiYTY5YmUyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eBKprFgOnm05SRpkLZcguNDK-2VAG2WAXsI9inJoM0E)
> > > ![微信图片_20241113124633](https://private-user-images.githubusercontent.com/26449654/385588848-f141205a-580c-4a52-b3fc-ba52cdd4fc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTU5ODEsIm5iZiI6MTczMTQ5NTY4MSwicGF0aCI6Ii8yNjQ0OTY1NC8zODU1ODg4NDgtZjE0MTIwNWEtNTgwYy00YTUyLWIzZmMtYmE1MmNkZDRmYzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzN2Y0NjEzYmFmMjdiOWJjOGRiM2Y0MmZhOTIwNTBmYzVlM2M4ZGE4MDU4ZTQwZWFkMGJhZTU4NjZjZjJjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hCb4EYteM3ED-OvszgS7lbgyNlgLX6adgLP3jnVHU9s)
> 
> <img alt="图片" width="1153" src="https://private-user-images.githubusercontent.com/186799862/385728352-45a19106-369f-4540-9366-99b850a241d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQxMjQsIm5iZiI6MTczMTUwMzgyNCwicGF0aCI6Ii8xODY3OTk4NjIvMzg1NzI4MzUyLTQ1YTE5MTA2LTM2OWYtNDU0MC05MzY2LTk5Yjg1MGEyNDFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMzE3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmRiZTkzZTdlOWE2YjgzODhjYWY4NWY2NjVlOGQ0OTZkNzg2NDZhZDMxZjBlMTIyOTY0MjNkNTkyMThkZDRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZioezMZBbP1LvZuO3zFdtCX7Pk3Dzhe2ulm9_E6Pyt0"> 目录下的文件和对应的参数应该如图，需要加上相对路径才能找到运行程序，并且windows下的可执行文件以.exe结尾。

已测试，正常了，谢谢！
