### ISSUE TITLE
Feature request: Test nodes with SNI

### ISSUE THREAD

**Issue by oknchm** [Kdwkakcs/singtools#3]
If it's possible, hope you can add a feature to test nodes with a user-provided SNI (server name indication). 

Reason for this is after testing with `singtool`, the filtered nodes are working by default, but when supplied with an SNI, some of them don't work. I do this test one by one and it can be very time consuming. This feature would help a lot. Thank you.

**Comment by Kdwkakcs** [comment]
I'm not familiar with SNI. If it's convenient, could you provide the process you use for adding and testing SNI?  this would help me test it.

**Comment by oknchm** [comment]
I just manually change the SNI (and sometimes the transfer protocol host, if applicable; in this case it's ws (websocket)). Using the v2rayNG Android app.

---

- Default configuration

<img src="https://github.com/user-attachments/assets/9207d80d-6c63-4bb9-bae9-e50216e0eae7" width="50%"/><img align="top" src="https://github.com/user-attachments/assets/6cf41f0b-423b-4f7a-ac98-a4ad7b5e9f25" width="50%"/>

- After changing the SNI 

<img src="https://github.com/user-attachments/assets/a234e835-ce58-429e-af77-e317008462f2" width="50%"/><img align="top" src="https://github.com/user-attachments/assets/7fdeaa3b-920b-40bb-bbe2-0cc16949b866" width="50%"/>

**Comment by Kdwkakcs** [comment]
Can you tell the SNI parameter in singbox, i don't known which corresponding to this. maybe you can change the `ws path` in singbox config manually or other tools, such as python, and then run `singtools` in the changed config.

**Comment by oknchm** [comment]
SNI is `server_name` under `tls`. It took a while but already found a way to change SNI in the singbox config. Thanks anyway. :)
